png("plot3.png", width=480, height=480)
plot(hpc1$Time,hpc1$Sub_metering_1,type="n",xlab="",ylab="Energy sub metering")
with(hpc1,lines(Time,as.numeric(Sub_metering_1)))
with(hpc1,lines(Time,as.numeric(Sub_metering_2),col="red"))
with(hpc1,lines(Time,as.numeric(Sub_metering_3),col="blue"))
legend("topright", lty=1, col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
dev.off()
